version: 2
jobs:
  build:
    machine:
        enabled: true
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
              sudo apt-get update
              sudo apt-get -y install wget zip unzip
      - run:
          name: Download Godot 3.2.2
          command: |
              wget -q https://downloads.tuxfamily.org/godotengine/3.2.2/Godot_v3.2.2-stable_linux_headless.64.zip
              unzip Godot_v3.2.2-stable_linux_headless.64.zip
              mv Godot_v3.2.2-stable_linux_headless.64 godot
              chmod +x godot
      - run:
          name: Download Godot 3.2.2 Export Templates
          command: |
              wget -q https://downloads.tuxfamily.org/godotengine/3.2.2/Godot_v3.2.2-stable_export_templates.tpz
              mkdir -p ~/.local/share/godot/templates
              unzip Godot_v3.2.2-stable_export_templates.tpz -d ~/.local/share/godot/templates
              mv ~/.local/share/godot/templates/templates ~/.local/share/godot/templates/3.2.2.stable
      - run:
          name: Export win64 build
          command: |
              mkdir win64
              ./godot --path project.godot --export win64 "win64/Pizza Awareness.exe"
              zip win64.zip win64/*
      - run:
          name: Export linux64 build
          command: |
              mkdir linux64
              ./godot --export linux64 --path project.godot "linux64/Pizza Awareness"
              zip linux64.zip linux64/*

      - run:
          name: Export mac build
          command: |
              ./godot --export macos --path project.godot "Pizza Awareness-mac"
              mv "Pizza Awareness-mac" "Pizza Awareness-mac.zip"
      - run:
          name: Export win32 build
          command: |
              mkdir win32
              ./godot --export win32 --path project.godot "win32/Pizza Awareness.exe"
              zip win32.zip win32/*
      - run:
          name: Export linux32 build
          command: |
              mkdir linux32
              ./godot --export linux32 --path project.godot "linux32/Pizza Awareness"
              zip linux32.zip linux32/*            
              
      - store_artifacts:
           path: win64.zip
           destination: win64.zip
        
      - store_artifacts:
           path: win32.zip
           destination: win32.zip
        
      - store_artifacts:
           path: linux64.zip
           destination: linux64.zip
        
      - store_artifacts:
           path: linux32.zip
           destination: linux32.zip
        
      - store_artifacts:
           path: Pizza Awareness-mac.zip
           destination: Pizza Awareness-mac.zip